from typing import List
from app.models.job import Job, Tag
from sqlalchemy.orm import Session

class TagService:
    def __init__(self, db: Session):
        self.db = db

    def _to_title_case(self, text: str) -> str:
        """Convert text to title case with proper formatting"""
        # Handle special cases
        special_cases = {
            'api': 'API',
            'aws': 'AWS',
            'sql': 'SQL',
            'saas': 'SaaS',
            'ai': 'AI',
            'ml': 'ML',
            'nosql': 'NoSQL',
            'nodejs': 'Node.js',
            'node.js': 'Node.js',
            'reactjs': 'React',
            'vuejs': 'Vue.js',
            'nextjs': 'Next.js',
            'ios': 'iOS',
            'android': 'Android',
            'ui': 'UI',
            'ux': 'UX',
            'devops': 'DevOps',
            'ci/cd': 'CI/CD',
            'rest': 'REST',
            'graphql': 'GraphQL',
            'json': 'JSON',
            'xml': 'XML',
            'html': 'HTML',
            'css': 'CSS',
            'http': 'HTTP',
            'https': 'HTTPS',
            'ssl': 'SSL',
            'tls': 'TLS',
            'jwt': 'JWT',
            'oauth': 'OAuth',
            'sdk': 'SDK',
            'ide': 'IDE',
            'cli': 'CLI',
            'gui': 'GUI',
            'orm': 'ORM',
            'crm': 'CRM',
            'erp': 'ERP',
            'bi': 'BI',
            'etl': 'ETL',
            'olap': 'OLAP',
            'cpu': 'CPU',
            'gpu': 'GPU',
            'ram': 'RAM',
            'ssd': 'SSD',
            'hdd': 'HDD',
            'url': 'URL',
            'uri': 'URI',
            'dns': 'DNS',
            'cdn': 'CDN',
            'vpc': 'VPC',
            'vpn': 'VPN',
            'ldap': 'LDAP',
            'ad': 'AD',
            'sso': 'SSO',
            'saml': 'SAML',
            'rbac': 'RBAC',
            'gdpr': 'GDPR',
            'hipaa': 'HIPAA',
            'soc2': 'SOC 2',
            'iso': 'ISO',
            'kpi': 'KPI',
            'roi': 'ROI',
            'sla': 'SLA',
            'rto': 'RTO',
            'rpo': 'RPO',
            'mttr': 'MTTR',
            'mtbf': 'MTBF',
            'ci': 'CI',
            'cd': 'CD',
            'iac': 'IaC',
            'paas': 'PaaS',
            'iaas': 'IaaS',
            'faas': 'FaaS',
            'draas': 'DRaaS',
            'bcdr': 'BCDR',
        }

        lower_text = text.lower()
        if lower_text in special_cases:
            return special_cases[lower_text]

        # Standard title case
        return text.title()

    def extract_tags_from_job(self, job: Job) -> List[Tag]:
        """Extract tags from job title and description"""
        tags = []
        text = f"{job.title} {job.description}".lower()

        # Common tech skills with display names (proper capitalization)
        tech_skills_map = {
            'python': 'Python',
            'javascript': 'JavaScript',
            'java': 'Java',
            'react': 'React',
            'reactjs': 'React',
            'node.js': 'Node.js',
            'nodejs': 'Node.js',
            'aws': 'AWS',
            'docker': 'Docker',
            'kubernetes': 'Kubernetes',
            'k8s': 'Kubernetes',
            'sql': 'SQL',
            'mysql': 'MySQL',
            'postgresql': 'PostgreSQL',
            'postgres': 'PostgreSQL',
            'mongodb': 'MongoDB',
            'typescript': 'TypeScript',
            'go': 'Go',
            'golang': 'Go',
            'rust': 'Rust',
            'swift': 'Swift',
            'kotlin': 'Kotlin',
            'scala': 'Scala',
            'ruby': 'Ruby',
            'rails': 'Rails',
            'php': 'PHP',
            'laravel': 'Laravel',
            'django': 'Django',
            'flask': 'Flask',
            'fastapi': 'FastAPI',
            'spring': 'Spring',
            'springboot': 'Spring Boot',
            'vue': 'Vue.js',
            'vuejs': 'Vue.js',
            'angular': 'Angular',
            'svelte': 'Svelte',
            'next.js': 'Next.js',
            'nextjs': 'Next.js',
            'nuxt': 'Nuxt.js',
            'nuxtjs': 'Nuxt.js',
            'express': 'Express.js',
            'nest': 'NestJS',
            'nestjs': 'NestJS',
            'graphql': 'GraphQL',
            'redis': 'Redis',
            'kafka': 'Kafka',
            'rabbitmq': 'RabbitMQ',
            'elasticsearch': 'Elasticsearch',
            'terraform': 'Terraform',
            'ansible': 'Ansible',
            'jenkins': 'Jenkins',
            'github actions': 'GitHub Actions',
            'gitlab ci': 'GitLab CI',
            'circleci': 'CircleCI',
            'travis': 'Travis CI',
            'prometheus': 'Prometheus',
            'grafana': 'Grafana',
            'datadog': 'Datadog',
            'splunk': 'Splunk',
            'elk': 'ELK Stack',
            'new relic': 'New Relic',
            'machine learning': 'Machine Learning',
            'ml': 'Machine Learning',
            'deep learning': 'Deep Learning',
            'ai': 'AI',
            'artificial intelligence': 'AI',
            'data science': 'Data Science',
            'data scientist': 'Data Science',
            'data engineering': 'Data Engineering',
            'data engineer': 'Data Engineering',
            'data analytics': 'Data Analytics',
            'data analysis': 'Data Analysis',
            'business intelligence': 'Business Intelligence',
            'bi': 'BI',
            'nlp': 'NLP',
            'computer vision': 'Computer Vision',
            'tensorflow': 'TensorFlow',
            'pytorch': 'PyTorch',
            'scikit-learn': 'Scikit-learn',
            'pandas': 'Pandas',
            'numpy': 'NumPy',
            'jupyter': 'Jupyter',
            'tableau': 'Tableau',
            'power bi': 'Power BI',
            'looker': 'Looker',
            'devops': 'DevOps',
            'sre': 'SRE',
            'platform engineering': 'Platform Engineering',
            'cloud': 'Cloud',
            'aws lambda': 'AWS Lambda',
            'azure': 'Azure',
            'gcp': 'GCP',
            'google cloud': 'Google Cloud',
            'serverless': 'Serverless',
            'microservices': 'Microservices',
            'rest': 'REST',
            'restful': 'REST API',
            'api': 'API',
            'soap': 'SOAP',
            'grpc': 'gRPC',
            'websockets': 'WebSockets',
            'oauth': 'OAuth',
            'jwt': 'JWT',
            'ssl': 'SSL',
            'tls': 'TLS',
            'encryption': 'Encryption',
            'cybersecurity': 'Cybersecurity',
            'security': 'Security',
            'penetration testing': 'Penetration Testing',
            'linux': 'Linux',
            'ubuntu': 'Ubuntu',
            'centos': 'CentOS',
            'debian': 'Debian',
            'redhat': 'Red Hat',
            'windows': 'Windows',
            'macos': 'macOS',
            'unix': 'Unix',
            'bash': 'Bash',
            'shell': 'Shell Scripting',
            'powershell': 'PowerShell',
            'git': 'Git',
            'github': 'GitHub',
            'gitlab': 'GitLab',
            'bitbucket': 'Bitbucket',
            'jira': 'Jira',
            'confluence': 'Confluence',
            'trello': 'Trello',
            'asana': 'Asana',
            'notion': 'Notion',
            'slack': 'Slack',
            'teams': 'Microsoft Teams',
            'agile': 'Agile',
            'scrum': 'Scrum',
            'kanban': 'Kanban',
            'lean': 'Lean',
            'xp': 'Extreme Programming',
            'ci/cd': 'CI/CD',
            'cicd': 'CI/CD',
            'continuous integration': 'CI/CD',
            'continuous deployment': 'CI/CD',
            'iac': 'Infrastructure as Code',
            'infrastructure as code': 'Infrastructure as Code',
            'containers': 'Containers',
            'containerization': 'Containerization',
            'helm': 'Helm',
            'istio': 'Istio',
            'linkerd': 'Linkerd',
            'consul': 'Consul',
            'vault': 'Vault',
            'nginx': 'Nginx',
            'apache': 'Apache',
            'tomcat': 'Tomcat',
            'iis': 'IIS',
            'cdn': 'CDN',
            'load balancer': 'Load Balancing',
            'caching': 'Caching',
            'redis cache': 'Redis Cache',
            'memcached': 'Memcached',
            'cdn': 'CDN',
            'cloudfront': 'CloudFront',
            'cloudflare': 'Cloudflare',
            'fastly': 'Fastly',
            'heroku': 'Heroku',
            'vercel': 'Vercel',
            'netlify': 'Netlify',
            'firebase': 'Firebase',
            'supabase': 'Supabase',
            'aws amplify': 'AWS Amplify',
            'mobile': 'Mobile',
            'ios': 'iOS',
            'android': 'Android',
            'react native': 'React Native',
            'flutter': 'Flutter',
            'swiftui': 'SwiftUI',
            'jetpack compose': 'Jetpack Compose',
            'xamarin': 'Xamarin',
            'unity': 'Unity',
            'unreal': 'Unreal Engine',
            'game development': 'Game Development',
            'web development': 'Web Development',
            'frontend': 'Frontend',
            'backend': 'Backend',
            'fullstack': 'Full Stack',
            'full stack': 'Full Stack',
            'ui': 'UI',
            'ux': 'UX',
            'ui/ux': 'UI/UX',
            'design': 'Design',
            'figma': 'Figma',
            'sketch': 'Sketch',
            'adobe xd': 'Adobe XD',
            'photoshop': 'Photoshop',
            'illustrator': 'Illustrator',
            'blender': 'Blender',
            'maya': 'Maya',
            '3d': '3D Modeling',
            'animation': 'Animation',
            'video editing': 'Video Editing',
            'premiere': 'Premiere Pro',
            'after effects': 'After Effects',
            'blockchain': 'Blockchain',
            'web3': 'Web3',
            'ethereum': 'Ethereum',
            'solidity': 'Solidity',
            'smart contracts': 'Smart Contracts',
            'defi': 'DeFi',
            'nft': 'NFT',
            'cryptocurrency': 'Cryptocurrency',
            'bitcoin': 'Bitcoin',
            'qa': 'QA',
            'testing': 'Testing',
            'automation': 'Automation',
            'selenium': 'Selenium',
            'cypress': 'Cypress',
            'playwright': 'Playwright',
            'jest': 'Jest',
            'mocha': 'Mocha',
            'junit': 'JUnit',
            'pytest': 'Pytest',
            'cucumber': 'Cucumber',
            'cicd': 'CI/CD',
            'tdd': 'TDD',
            'bdd': 'BDD',
            'performance testing': 'Performance Testing',
            'load testing': 'Load Testing',
            'integration testing': 'Integration Testing',
            'e2e': 'E2E Testing',
            'unit testing': 'Unit Testing',
            'integration testing': 'Integration Testing',
        }

        # Standard job titles with proper capitalization
        job_titles_map = {
            'software engineer': 'Software Engineer',
            'software developer': 'Software Developer',
            'senior software engineer': 'Senior Software Engineer',
            'senior software developer': 'Senior Software Developer',
            'lead software engineer': 'Lead Software Engineer',
            'staff software engineer': 'Staff Software Engineer',
            'principal software engineer': 'Principal Software Engineer',
            'data scientist': 'Data Scientist',
            'data analyst': 'Data Analyst',
            'data engineer': 'Data Engineer',
            'senior data scientist': 'Senior Data Scientist',
            'senior data analyst': 'Senior Data Analyst',
            'senior data engineer': 'Senior Data Engineer',
            'machine learning engineer': 'Machine Learning Engineer',
            'ml engineer': 'ML Engineer',
            'ai engineer': 'AI Engineer',
            'devops engineer': 'DevOps Engineer',
            'site reliability engineer': 'Site Reliability Engineer',
            'sre': 'SRE',
            'platform engineer': 'Platform Engineer',
            'cloud engineer': 'Cloud Engineer',
            'infrastructure engineer': 'Infrastructure Engineer',
            'security engineer': 'Security Engineer',
            'cybersecurity engineer': 'Cybersecurity Engineer',
            'network engineer': 'Network Engineer',
            'systems engineer': 'Systems Engineer',
            'backend engineer': 'Backend Engineer',
            'backend developer': 'Backend Developer',
            'frontend engineer': 'Frontend Engineer',
            'frontend developer': 'Frontend Developer',
            'full stack engineer': 'Full Stack Engineer',
            'fullstack engineer': 'Full Stack Engineer',
            'full stack developer': 'Full Stack Developer',
            'fullstack developer': 'Full Stack Developer',
            'web developer': 'Web Developer',
            'mobile developer': 'Mobile Developer',
            'mobile engineer': 'Mobile Engineer',
            'ios developer': 'iOS Developer',
            'ios engineer': 'iOS Engineer',
            'android developer': 'Android Developer',
            'android engineer': 'Android Engineer',
            'react native developer': 'React Native Developer',
            'flutter developer': 'Flutter Developer',
            'game developer': 'Game Developer',
            'unity developer': 'Unity Developer',
            'qa engineer': 'QA Engineer',
            'quality assurance engineer': 'QA Engineer',
            'test engineer': 'Test Engineer',
            'automation engineer': 'Automation Engineer',
            'sdet': 'SDET',
            'product manager': 'Product Manager',
            'technical product manager': 'Technical Product Manager',
            'program manager': 'Program Manager',
            'project manager': 'Project Manager',
            'technical program manager': 'Technical Program Manager',
            'engineering manager': 'Engineering Manager',
            'engineering lead': 'Engineering Lead',
            'tech lead': 'Tech Lead',
            'team lead': 'Team Lead',
            'cto': 'CTO',
            'chief technology officer': 'CTO',
            'vp of engineering': 'VP of Engineering',
            'head of engineering': 'Head of Engineering',
            'director of engineering': 'Director of Engineering',
            'ux designer': 'UX Designer',
            'ui designer': 'UI Designer',
            'ui/ux designer': 'UI/UX Designer',
            'product designer': 'Product Designer',
            'graphic designer': 'Graphic Designer',
            'web designer': 'Web Designer',
            'interaction designer': 'Interaction Designer',
            'visual designer': 'Visual Designer',
            'motion designer': 'Motion Designer',
            'systems architect': 'Systems Architect',
            'software architect': 'Software Architect',
            'solutions architect': 'Solutions Architect',
            'enterprise architect': 'Enterprise Architect',
            'cloud architect': 'Cloud Architect',
            'data architect': 'Data Architect',
            'security architect': 'Security Architect',
            'technical architect': 'Technical Architect',
            'database administrator': 'Database Administrator',
            'dba': 'DBA',
            'sysadmin': 'Systems Administrator',
            'systems administrator': 'Systems Administrator',
            'network administrator': 'Network Administrator',
            'it administrator': 'IT Administrator',
            'it support': 'IT Support',
            'helpdesk': 'Helpdesk',
            'technical support': 'Technical Support',
            'customer support engineer': 'Customer Support Engineer',
            'sales engineer': 'Sales Engineer',
            'solutions engineer': 'Solutions Engineer',
            'pre-sales engineer': 'Pre-Sales Engineer',
            'business analyst': 'Business Analyst',
            'technical business analyst': 'Technical Business Analyst',
            'systems analyst': 'Systems Analyst',
            'financial analyst': 'Financial Analyst',
            'research analyst': 'Research Analyst',
            'marketing analyst': 'Marketing Analyst',
            'growth engineer': 'Growth Engineer',
            'seo specialist': 'SEO Specialist',
            'sem specialist': 'SEM Specialist',
            'content strategist': 'Content Strategist',
            'technical writer': 'Technical Writer',
            'documentation engineer': 'Documentation Engineer',
            'developer advocate': 'Developer Advocate',
            'developer relations': 'Developer Relations',
            'community manager': 'Community Manager',
            'open source maintainer': 'Open Source Maintainer',
            'scrum master': 'Scrum Master',
            'agile coach': 'Agile Coach',
            'release engineer': 'Release Engineer',
            'build engineer': 'Build Engineer',
            'performance engineer': 'Performance Engineer',
            'site performance engineer': 'Site Performance Engineer',
            'reliability engineer': 'Reliability Engineer',
            'analytics engineer': 'Analytics Engineer',
            'business intelligence engineer': 'BI Engineer',
            'bi developer': 'BI Developer',
            'etl developer': 'ETL Developer',
            'data warehouse engineer': 'Data Warehouse Engineer',
            'big data engineer': 'Big Data Engineer',
            'nlp engineer': 'NLP Engineer',
            'computer vision engineer': 'Computer Vision Engineer',
            'robotics engineer': 'Robotics Engineer',
            'embedded engineer': 'Embedded Engineer',
            'firmware engineer': 'Firmware Engineer',
            'hardware engineer': 'Hardware Engineer',
            'fpga engineer': 'FPGA Engineer',
            'asic engineer': 'ASIC Engineer',
            'chip design engineer': 'Chip Design Engineer',
            'vlsi': 'VLSI Engineer',
            'silicon engineer': 'Silicon Engineer',
        }

        # Common industries with proper capitalization
        industries_map = {
            'fintech': 'Fintech',
            'financial technology': 'Fintech',
            'healthcare': 'Healthcare',
            'health tech': 'Health Tech',
            'medtech': 'MedTech',
            'ecommerce': 'E-commerce',
            'e-commerce': 'E-commerce',
            'retail': 'Retail',
            'saas': 'SaaS',
            'software as a service': 'SaaS',
            'education': 'Education',
            'edtech': 'EdTech',
            'gaming': 'Gaming',
            'games': 'Gaming',
            'finance': 'Finance',
            'banking': 'Banking',
            'investment banking': 'Investment Banking',
            'insurance': 'Insurance',
            'insurtech': 'InsurTech',
            'manufacturing': 'Manufacturing',
            'automotive': 'Automotive',
            'aerospace': 'Aerospace',
            'defense': 'Defense',
            'government': 'Government',
            'public sector': 'Public Sector',
            'nonprofit': 'Nonprofit',
            'non-profit': 'Nonprofit',
            'energy': 'Energy',
            'renewable energy': 'Renewable Energy',
            'cleantech': 'CleanTech',
            'oil and gas': 'Oil & Gas',
            'telecommunications': 'Telecommunications',
            'telecom': 'Telecom',
            'media': 'Media',
            'entertainment': 'Entertainment',
            'streaming': 'Streaming',
            'social media': 'Social Media',
            'advertising': 'Advertising',
            'adtech': 'AdTech',
            'marketing': 'Marketing',
            'martech': 'MarTech',
            'real estate': 'Real Estate',
            'prop tech': 'PropTech',
            'proptech': 'PropTech',
            'logistics': 'Logistics',
            'supply chain': 'Supply Chain',
            'transportation': 'Transportation',
            'travel': 'Travel',
            'hospitality': 'Hospitality',
            'food delivery': 'Food Delivery',
            'agriculture': 'Agriculture',
            'agtech': 'AgTech',
            'construction': 'Construction',
            'contech': 'ConTech',
            'legal': 'Legal',
            'legal tech': 'LegalTech',
            'crypto': 'Cryptocurrency',
            'cryptocurrency': 'Cryptocurrency',
            'blockchain': 'Blockchain',
            'web3': 'Web3',
            'nft': 'NFT',
            'artificial intelligence': 'AI',
            'ai industry': 'AI',
            'machine learning industry': 'Machine Learning',
            'data science industry': 'Data Science',
            'quantum computing': 'Quantum Computing',
            'robotics': 'Robotics',
            'automation': 'Automation',
            'iot': 'IoT',
            'internet of things': 'IoT',
        }

        # Extract tech skills
        for skill_key, display_name in tech_skills_map.items():
            if skill_key in text:
                tag = self._get_or_create_tag(display_name, 'skill')
                if tag not in tags:
                    tags.append(tag)

        # Extract job titles (multi-word first, then single)
        # Sort by length (longest first) to prioritize specific titles
        sorted_titles = sorted(job_titles_map.items(), key=lambda x: len(x[0]), reverse=True)
        for title_key, display_name in sorted_titles:
            if title_key in text:
                tag = self._get_or_create_tag(display_name, 'role')
                if tag not in tags:
                    tags.append(tag)

        # Extract industries
        for industry_key, display_name in industries_map.items():
            if industry_key in text:
                tag = self._get_or_create_tag(display_name, 'industry')
                if tag not in tags:
                    tags.append(tag)

        return tags
    
    def _get_or_create_tag(self, name: str, category: str) -> Tag:
        tag = self.db.query(Tag).filter(Tag.name == name).first()
        if not tag:
            tag = Tag(name=name, category=category)
            self.db.add(tag)
            self.db.commit()
            self.db.refresh(tag)
        return tag
    
    def get_all_tags(self) -> List[Tag]:
        return self.db.query(Tag).all()
    
    def get_tags_by_category(self, category: str) -> List[Tag]:
        return self.db.query(Tag).filter(Tag.category == category).all()
