from typing import List
from app.models.job import Job, Tag
from sqlalchemy.orm import Session

class TagService:
    def __init__(self, db: Session):
        self.db = db

    def _to_title_case(self, text: str) -> str:
        """Convert text to title case with proper formatting"""
        # Handle special cases
        special_cases = {
            'api': 'API',
            'aws': 'AWS',
            'sql': 'SQL',
            'saas': 'SaaS',
            'ai': 'AI',
            'ml': 'ML',
            'nosql': 'NoSQL',
            'nodejs': 'Node.js',
            'node.js': 'Node.js',
            'reactjs': 'React',
            'vuejs': 'Vue.js',
            'nextjs': 'Next.js',
            'ios': 'iOS',
            'android': 'Android',
            'ui': 'UI',
            'ux': 'UX',
            'devops': 'DevOps',
            'ci/cd': 'CI/CD',
            'rest': 'REST',
            'graphql': 'GraphQL',
            'json': 'JSON',
            'xml': 'XML',
            'html': 'HTML',
            'css': 'CSS',
            'http': 'HTTP',
            'https': 'HTTPS',
            'ssl': 'SSL',
            'tls': 'TLS',
            'jwt': 'JWT',
            'oauth': 'OAuth',
            'sdk': 'SDK',
            'ide': 'IDE',
            'cli': 'CLI',
            'gui': 'GUI',
            'orm': 'ORM',
            'crm': 'CRM',
            'erp': 'ERP',
            'bi': 'BI',
            'etl': 'ETL',
            'olap': 'OLAP',
            'cpu': 'CPU',
            'gpu': 'GPU',
            'ram': 'RAM',
            'ssd': 'SSD',
            'hdd': 'HDD',
            'url': 'URL',
            'uri': 'URI',
            'dns': 'DNS',
            'cdn': 'CDN',
            'vpc': 'VPC',
            'vpn': 'VPN',
            'ldap': 'LDAP',
            'ad': 'AD',
            'sso': 'SSO',
            'saml': 'SAML',
            'rbac': 'RBAC',
            'gdpr': 'GDPR',
            'hipaa': 'HIPAA',
            'soc2': 'SOC 2',
            'iso': 'ISO',
            'kpi': 'KPI',
            'roi': 'ROI',
            'sla': 'SLA',
            'rto': 'RTO',
            'rpo': 'RPO',
            'mttr': 'MTTR',
            'mtbf': 'MTBF',
            'ci': 'CI',
            'cd': 'CD',
            'iac': 'IaC',
            'paas': 'PaaS',
            'iaas': 'IaaS',
            'faas': 'FaaS',
            'draas': 'DRaaS',
            'bcdr': 'BCDR',
        }

        lower_text = text.lower()
        if lower_text in special_cases:
            return special_cases[lower_text]

        # Standard title case
        return text.title()

    def extract_tags_from_job(self, job: Job) -> List[Tag]:
        """Extract tags from job title and description"""
        tags = []
        text = f"{job.title} {job.description}".lower()

        # Common tech skills with display names (proper capitalization)
        tech_skills_map = {
            'python': 'Python',
            'javascript': 'JavaScript',
            'java': 'Java',
            'react': 'React',
            'reactjs': 'React',
            'node.js': 'Node.js',
            'nodejs': 'Node.js',
            'aws': 'AWS',
            'docker': 'Docker',
            'kubernetes': 'Kubernetes',
            'k8s': 'Kubernetes',
            'sql': 'SQL',
            'mysql': 'MySQL',
            'postgresql': 'PostgreSQL',
            'postgres': 'PostgreSQL',
            'mongodb': 'MongoDB',
            'typescript': 'TypeScript',
            'go': 'Go',
            'golang': 'Go',
            'rust': 'Rust',
            'swift': 'Swift',
            'kotlin': 'Kotlin',
            'scala': 'Scala',
            'ruby': 'Ruby',
            'rails': 'Rails',
            'php': 'PHP',
            'laravel': 'Laravel',
            'django': 'Django',
            'flask': 'Flask',
            'fastapi': 'FastAPI',
            'spring': 'Spring',
            'springboot': 'Spring Boot',
            'vue': 'Vue.js',
            'vuejs': 'Vue.js',
            'angular': 'Angular',
            'svelte': 'Svelte',
            'next.js': 'Next.js',
            'nextjs': 'Next.js',
            'nuxt': 'Nuxt.js',
            'nuxtjs': 'Nuxt.js',
            'express': 'Express.js',
            'nest': 'NestJS',
            'nestjs': 'NestJS',
            'graphql': 'GraphQL',
            'redis': 'Redis',
            'kafka': 'Kafka',
            'rabbitmq': 'RabbitMQ',
            'elasticsearch': 'Elasticsearch',
            'terraform': 'Terraform',
            'ansible': 'Ansible',
            'jenkins': 'Jenkins',
            'github actions': 'GitHub Actions',
            'gitlab ci': 'GitLab CI',
            'circleci': 'CircleCI',
            'travis': 'Travis CI',
            'prometheus': 'Prometheus',
            'grafana': 'Grafana',
            'datadog': 'Datadog',
            'splunk': 'Splunk',
            'elk': 'ELK Stack',
            'new relic': 'New Relic',
            'machine learning': 'Machine Learning',
            'ml': 'Machine Learning',
            'deep learning': 'Deep Learning',
            'ai': 'AI',
            'artificial intelligence': 'AI',
            'data science': 'Data Science',
            'data scientist': 'Data Science',
            'data engineering': 'Data Engineering',
            'data engineer': 'Data Engineering',
            'data analytics': 'Data Analytics',
            'data analysis': 'Data Analysis',
            'business intelligence': 'Business Intelligence',
            'bi': 'BI',
            'nlp': 'NLP',
            'computer vision': 'Computer Vision',
            'tensorflow': 'TensorFlow',
            'pytorch': 'PyTorch',
            'scikit-learn': 'Scikit-learn',
            'pandas': 'Pandas',
            'numpy': 'NumPy',
            'jupyter': 'Jupyter',
            'tableau': 'Tableau',
            'power bi': 'Power BI',
            'looker': 'Looker',
            'devops': 'DevOps',
            'sre': 'SRE',
            'platform engineering': 'Platform Engineering',
            'cloud': 'Cloud',
            'aws lambda': 'AWS Lambda',
            'azure': 'Azure',
            'gcp': 'GCP',
            'google cloud': 'Google Cloud',
            'serverless': 'Serverless',
            'microservices': 'Microservices',
            'rest': 'REST',
            'restful': 'REST API',
            'api': 'API',
            'soap': 'SOAP',
            'grpc': 'gRPC',
            'websockets': 'WebSockets',
            'oauth': 'OAuth',
            'jwt': 'JWT',
            'ssl': 'SSL',
            'tls': 'TLS',
            'encryption': 'Encryption',
            'cybersecurity': 'Cybersecurity',
            'security': 'Security',
            'penetration testing': 'Penetration Testing',
            'linux': 'Linux',
            'ubuntu': 'Ubuntu',
            'centos': 'CentOS',
            'debian': 'Debian',
            'redhat': 'Red Hat',
            'windows': 'Windows',
            'macos': 'macOS',
            'unix': 'Unix',
            'bash': 'Bash',
            'shell': 'Shell Scripting',
            'powershell': 'PowerShell',
            'git': 'Git',
            'github': 'GitHub',
            'gitlab': 'GitLab',
            'bitbucket': 'Bitbucket',
            'jira': 'Jira',
            'confluence': 'Confluence',
            'trello': 'Trello',
            'asana': 'Asana',
            'notion': 'Notion',
            'slack': 'Slack',
            'teams': 'Microsoft Teams',
            'agile': 'Agile',
            'scrum': 'Scrum',
            'kanban': 'Kanban',
            'lean': 'Lean',
            'xp': 'Extreme Programming',
            'ci/cd': 'CI/CD',
            'cicd': 'CI/CD',
            'continuous integration': 'CI/CD',
            'continuous deployment': 'CI/CD',
            'iac': 'Infrastructure as Code',
            'infrastructure as code': 'Infrastructure as Code',
            'containers': 'Containers',
            'containerization': 'Containerization',
            'helm': 'Helm',
            'istio': 'Istio',
            'linkerd': 'Linkerd',
            'consul': 'Consul',
            'vault': 'Vault',
            'nginx': 'Nginx',
            'apache': 'Apache',
            'tomcat': 'Tomcat',
            'iis': 'IIS',
            'cdn': 'CDN',
            'load balancer': 'Load Balancing',
            'caching': 'Caching',
            'redis cache': 'Redis Cache',
            'memcached': 'Memcached',
            'cdn': 'CDN',
            'cloudfront': 'CloudFront',
            'cloudflare': 'Cloudflare',
            'fastly': 'Fastly',
            'heroku': 'Heroku',
            'vercel': 'Vercel',
            'netlify': 'Netlify',
            'firebase': 'Firebase',
            'supabase': 'Supabase',
            'aws amplify': 'AWS Amplify',
            'mobile': 'Mobile',
            'ios': 'iOS',
            'android': 'Android',
            'react native': 'React Native',
            'flutter': 'Flutter',
            'swiftui': 'SwiftUI',
            'jetpack compose': 'Jetpack Compose',
            'xamarin': 'Xamarin',
            'unity': 'Unity',
            'unreal': 'Unreal Engine',
            'game development': 'Game Development',
            'web development': 'Web Development',
            'frontend': 'Frontend',
            'backend': 'Backend',
            'fullstack': 'Full Stack',
            'full stack': 'Full Stack',
            'ui': 'UI',
            'ux': 'UX',
            'ui/ux': 'UI/UX',
            'design': 'Design',
            'figma': 'Figma',
            'sketch': 'Sketch',
            'adobe xd': 'Adobe XD',
            'photoshop': 'Photoshop',
            'illustrator': 'Illustrator',
            'blender': 'Blender',
            'maya': 'Maya',
            '3d': '3D Modeling',
            'animation': 'Animation',
            'video editing': 'Video Editing',
            'premiere': 'Premiere Pro',
            'after effects': 'After Effects',
            'blockchain': 'Blockchain',
            'web3': 'Web3',
            'ethereum': 'Ethereum',
            'solidity': 'Solidity',
            'smart contracts': 'Smart Contracts',
            'defi': 'DeFi',
            'nft': 'NFT',
            'cryptocurrency': 'Cryptocurrency',
            'bitcoin': 'Bitcoin',
            'qa': 'QA',
            'testing': 'Testing',
            'automation': 'Automation',
            'selenium': 'Selenium',
            'cypress': 'Cypress',
            'playwright': 'Playwright',
            'jest': 'Jest',
            'mocha': 'Mocha',
            'junit': 'JUnit',
            'pytest': 'Pytest',
            'cucumber': 'Cucumber',
            'cicd': 'CI/CD',
            'tdd': 'TDD',
            'bdd': 'BDD',
            'performance testing': 'Performance Testing',
            'load testing': 'Load Testing',
            'integration testing': 'Integration Testing',
            'e2e': 'E2E Testing',
            'unit testing': 'Unit Testing',
            # Additional modern tech skills
            'snowflake': 'Snowflake',
            'databricks': 'Databricks',
            'bigquery': 'BigQuery',
            'redshift': 'Redshift',
            'cassandra': 'Cassandra',
            'dynamodb': 'DynamoDB',
            'cosmos db': 'Cosmos DB',
            'firebase': 'Firebase',
            'neo4j': 'Neo4j',
            'couchbase': 'Couchbase',
            'cockroachdb': 'CockroachDB',
            'timescaledb': 'TimescaleDB',
            'influxdb': 'InfluxDB',
            'c#': 'C#',
            'csharp': 'C#',
            '.net': '.NET',
            'dotnet': '.NET',
            'asp.net': 'ASP.NET',
            'blazor': 'Blazor',
            'xamarin': 'Xamarin',
            'maui': '.NET MAUI',
            'wpf': 'WPF',
            'winforms': 'WinForms',
            'entity framework': 'Entity Framework',
            'ef core': 'EF Core',
            'linq': 'LINQ',
            'nuget': 'NuGet',
            'powershell': 'PowerShell',
            'active directory': 'Active Directory',
            'sharepoint': 'SharePoint',
            'exchange': 'Exchange',
            'hugging face': 'Hugging Face',
            'langchain': 'LangChain',
            'llama': 'LLaMA',
            'openai': 'OpenAI',
            'gpt': 'GPT',
            'claude': 'Claude',
            'anthropic': 'Anthropic',
            'bert': 'BERT',
            'transformers': 'Transformers',
            'stable diffusion': 'Stable Diffusion',
            'open cv': 'OpenCV',
            'opencv': 'OpenCV',
            'kubeflow': 'Kubeflow',
            'mlflow': 'MLflow',
            'dvc': 'DVC',
            'label studio': 'Label Studio',
            'argocd': 'ArgoCD',
            'argo cd': 'ArgoCD',
            'flux': 'Flux',
            'pulumi': 'Pulumi',
            'crossplane': 'Crossplane',
            'keptn': 'Keptn',
            'flagger': 'Flagger',
            'karpenter': 'Karpenter',
            'cluster autoscaler': 'Cluster Autoscaler',
            'keda': 'KEDA',
            'knative': 'Knative',
            'dapr': 'Dapr',
            'tanzu': 'Tanzu',
            'openshift': 'OpenShift',
            'rancher': 'Rancher',
            'portainer': 'Portainer',
            'longhorn': 'Longhorn',
            'harbor': 'Harbor',
            'spinnaker': 'Spinnaker',
            'tekton': 'Tekton',
            'buildpacks': 'Buildpacks',
            'packer': 'Packer',
            'vagrant': 'Vagrant',
            'vsphere': 'vSphere',
            'proxmox': 'Proxmox',
            'kvm': 'KVM',
            'qemu': 'QEMU',
            'libvirt': 'libvirt',
            'xen': 'Xen',
            'hyper-v': 'Hyper-V',
            'hyperv': 'Hyper-V',
            'storybook': 'Storybook',
            'chromatic': 'Chromatic',
            'loki': 'Loki',
            'msw': 'MSW',
            'react testing library': 'React Testing Library',
            'rtl': 'React Testing Library',
            'testing library': 'Testing Library',
            'enzyme': 'Enzyme',
            'webpack': 'Webpack',
            'vite': 'Vite',
            'rollup': 'Rollup',
            'esbuild': 'esbuild',
            'swc': 'SWC',
            'babel': 'Babel',
            'parcel': 'Parcel',
            'turbo': 'Turborepo',
            'turborepo': 'Turborepo',
            'nx': 'Nx',
            'lerna': 'Lerna',
            'changesets': 'Changesets',
            'semantic release': 'Semantic Release',
            'husky': 'Husky',
            'lint-staged': 'lint-staged',
            'prettier': 'Prettier',
            'eslint': 'ESLint',
            'stylelint': 'Stylelint',
            'commitlint': 'commitlint',
            'conventional commits': 'Conventional Commits',
            'shadcn': 'shadcn/ui',
            'shadcn/ui': 'shadcn/ui',
            'radix': 'Radix UI',
            'radix ui': 'Radix UI',
            'headless ui': 'Headless UI',
            'chakra': 'Chakra UI',
            'chakra ui': 'Chakra UI',
            'mantine': 'Mantine',
            'mui': 'Material UI',
            'material ui': 'Material UI',
            'vuetify': 'Vuetify',
            'quasar': 'Quasar',
            'bootstrap': 'Bootstrap',
            'tailwind': 'Tailwind CSS',
            'tailwindcss': 'Tailwind CSS',
            'sass': 'Sass',
            'scss': 'SCSS',
            'less': 'Less',
            'stylus': 'Stylus',
            'emotion': 'Emotion',
            'styled-components': 'styled-components',
            'styled components': 'styled-components',
            'framer motion': 'Framer Motion',
            'gsap': 'GSAP',
            'three.js': 'Three.js',
            'threejs': 'Three.js',
            'babylon.js': 'Babylon.js',
            'babylonjs': 'Babylon.js',
            'd3': 'D3.js',
            'd3.js': 'D3.js',
            'chart.js': 'Chart.js',
            'chartjs': 'Chart.js',
            'recharts': 'Recharts',
            'highcharts': 'Highcharts',
            'plotly': 'Plotly',
            'leaflet': 'Leaflet',
            'mapbox': 'Mapbox',
            'google maps': 'Google Maps API',
            'stripe': 'Stripe',
            'paypal': 'PayPal',
            'square': 'Square',
            'plaid': 'Plaid',
            'twilio': 'Twilio',
            'sendgrid': 'SendGrid',
            'mailgun': 'Mailgun',
            'postmark': 'Postmark',
            'aws ses': 'AWS SES',
            'sns': 'AWS SNS',
            'sqs': 'AWS SQS',
            'eventbridge': 'EventBridge',
            'step functions': 'Step Functions',
            'app sync': 'AppSync',
            'appsync': 'AppSync',
            'amplify': 'AWS Amplify',
            'cdk': 'AWS CDK',
            'sam': 'AWS SAM',
            'cloudformation': 'CloudFormation',
            'azure devops': 'Azure DevOps',
            'azure pipelines': 'Azure Pipelines',
            'github packages': 'GitHub Packages',
            'npm': 'npm',
            'yarn': 'Yarn',
            'pnpm': 'pnpm',
            'nvm': 'nvm',
            'volta': 'Volta',
            'fnm': 'fnm',
            'asdf': 'asdf',
            'mise': 'mise',
            'homebrew': 'Homebrew',
            'chocolatey': 'Chocolatey',
            'winget': 'winget',
            'scoop': 'Scoop',
            'apt': 'APT',
            'yum': 'YUM',
            'pacman': 'pacman',
            'nix': 'Nix',
            'guix': 'Guix',
            'flatpak': 'Flatpak',
            'snap': 'Snap',
            'appimage': 'AppImage',
            'docker compose': 'Docker Compose',
            'docker-compose': 'Docker Compose',
            'dockerfile': 'Dockerfile',
            'compose': 'Docker Compose',
            'buildkit': 'BuildKit',
            'kaniko': 'Kaniko',
            'img': 'img',
            'buildah': 'Buildah',
            'podman': 'Podman',
            'skopeo': 'Skopeo',
            'cri-o': 'CRI-O',
            'containerd': 'containerd',
            'runc': 'runc',
            'gvisor': 'gVisor',
            'kata containers': 'Kata Containers',
            'firecracker': 'Firecracker',
            'microvm': 'MicroVM',
            'qemu': 'QEMU',
            'virt-manager': 'virt-manager',
            'cockpit': 'Cockpit',
            'webmin': 'Webmin',
            ' Ajenti': 'Ajenti',
            'fastapi': 'FastAPI',
            'flask': 'Flask',
            'django': 'Django',
            'tornado': 'Tornado',
            'sanic': 'Sanic',
            'quart': 'Quart',
            'aiohttp': 'aiohttp',
            'httpx': 'HTTPX',
            'requests': 'Requests',
            'urllib': 'urllib',
            'beautiful soup': 'Beautiful Soup',
            'beautifulsoup': 'Beautiful Soup',
            'scrapy': 'Scrapy',
            'selenium': 'Selenium',
            'playwright': 'Playwright',
            'puppeteer': 'Puppeteer',
            'cypress': 'Cypress',
            'webdriver': 'WebDriver',
            'appium': 'Appium',
            'calabash': 'Calabash',
            'detox': 'Detox',
            'espresso': 'Espresso',
            'xctest': 'XCTest',
            'kif': 'KIF',
            ' EarlGrey': 'EarlGrey',
            'karma': 'Karma',
            'jasmine': 'Jasmine',
            'qunit': 'QUnit',
            'protractor': 'Protractor',
            'nightwatch': 'Nightwatch',
            'webdriverio': 'WebdriverIO',
            'codeceptjs': 'CodeceptJS',
            'testcafe': 'TestCafe',
            'taiko': 'Taiko',
            'gauge': 'Gauge',
            'robot framework': 'Robot Framework',
            'cucumber': 'Cucumber',
            'gherkin': 'Gherkin',
            'postman': 'Postman',
            'insomnia': 'Insomnia',
            'hoppscotch': 'Hoppscotch',
            'httpie': 'HTTPie',
            'curl': 'cURL',
            'wget': 'Wget',
            'grpcurl': 'grpcurl',
            'evans': 'Evans',
            'bloomrpc': 'BloomRPC',
            'krew': 'Krew',
            'kubectl': 'kubectl',
            'k9s': 'k9s',
            'kubectx': 'kubectx',
            'kubens': 'kubens',
            'stern': 'Stern',
            'kail': 'kail',
            'fluxcd': 'Flux',
            'sealed secrets': 'Sealed Secrets',
            'external secrets': 'External Secrets Operator',
            'cert-manager': 'cert-manager',
            'lets encrypt': "Let's Encrypt",
            'letsencrypt': "Let's Encrypt",
            'acme': 'ACME',
            'traefik': 'Traefik',
            'envoy': 'Envoy',
            'contour': 'Contour',
            'ingress-nginx': 'Ingress-NGINX',
            'haproxy': 'HAProxy',
            'varnish': 'Varnish',
            'squid': 'Squid',
            'modsecurity': 'ModSecurity',
            'owasp': 'OWASP',
            'burp suite': 'Burp Suite',
            'metasploit': 'Metasploit',
            'nmap': 'Nmap',
            'wireshark': 'Wireshark',
            'nessus': 'Nessus',
            'qualys': 'Qualys',
            'rapid7': 'Rapid7',
            'tenable': 'Tenable',
            'snyk': 'Snyk',
            'sonarqube': 'SonarQube',
            'sonarcloud': 'SonarCloud',
            'checkmarx': 'Checkmarx',
            'veracode': 'Veracode',
            'blackduck': 'Black Duck',
            'whitesource': 'WhiteSource',
            'fossa': 'FOSSA',
            'dependabot': 'Dependabot',
            'renovate': 'Renovate',
            'safety': 'Safety',
            'bandit': 'Bandit',
            'semgrep': 'Semgrep',
            'brakeman': 'Brakeman',
            'gosec': 'gosec',
            'tfsec': 'tfsec',
            'checkov': 'Checkov',
            'terrascan': 'Terrascan',
            'kubescape': 'Kubescape',
            'trivy': 'Trivy',
            'grype': 'Grype',
            'syft': 'Syft',
            'cosign': 'Cosign',
            'sigstore': 'Sigstore',
            'fulcio': 'Fulcio',
            'rekor': 'Rekor',
            'notation': 'Notation',
            'oras': 'ORAS',
            'distribution': 'Distribution',
            'harbor': 'Harbor',
            'quay': 'Quay',
            'github container registry': 'GitHub Container Registry',
            'ghcr': 'GHCR',
            'amazon ecr': 'Amazon ECR',
            'ecr': 'ECR',
            'google container registry': 'Google Container Registry',
            'gcr': 'GCR',
            'azure container registry': 'Azure Container Registry',
            'acr': 'ACR',
            'docker hub': 'Docker Hub',
            'gitlab container registry': 'GitLab Container Registry',
            'jfrog artifactory': 'JFrog Artifactory',
            'artifactory': 'Artifactory',
            'sonatype nexus': 'Sonatype Nexus',
            'nexus': 'Nexus',
            'cloudsmith': 'Cloudsmith',
            'packagecloud': 'Packagecloud',
            'gemfury': 'Gemfury',
            'chartmuseum': 'ChartMuseum',
            'rancher': 'Rancher',
            'portainer': 'Portainer',
            'openshift': 'OpenShift',
            'okd': 'OKD',
            'minikube': 'Minikube',
            'kind': 'kind',
            'k3s': 'K3s',
            'k3d': 'k3d',
            'microk8s': 'MicroK8s',
            'docker desktop': 'Docker Desktop',
            'rancher desktop': 'Rancher Desktop',
            'colima': 'Colima',
            'lima': 'Lima',
            'vz': 'vz',
            'utern': 'utern',
            'telepresence': 'Telepresence',
            'mirrord': 'mirrord',
            'istio': 'Istio',
            'linkerd': 'Linkerd',
            'consul': 'Consul',
            'consul connect': 'Consul Connect',
            'traefik mesh': 'Traefik Mesh',
            'osm': 'OSM',
            'kuma': 'Kuma',
            'cilium': 'Cilium',
            'hubble': 'Hubble',
            'tetragon': 'Tetragon',
            'falco': 'Falco',
            'sysdig': 'Sysdig',
            'tracee': 'Tracee',
            'pixie': 'Pixie',
            'groundcover': 'Groundcover',
            'deepflow': 'DeepFlow',
            'netdata': 'Netdata',
            'elastic': 'Elastic Stack',
            'elasticsearch': 'Elasticsearch',
            'logstash': 'Logstash',
            'kibana': 'Kibana',
            'beats': 'Beats',
            'apm': 'APM',
            'jaeger': 'Jaeger',
            'zipkin': 'Zipkin',
            'tempo': 'Tempo',
            'loki': 'Loki',
            'cortex': 'Cortex',
            'thanos': 'Thanos',
            'victoria metrics': 'VictoriaMetrics',
            'mimir': 'Mimir',
            'phlare': 'Phlare',
            'pyroscope': 'Pyroscope',
            'parca': 'Parca',
            'kindling': 'Kindling',
            'otel': 'OpenTelemetry',
            'opentelemetry': 'OpenTelemetry',
            'opencensus': 'OpenCensus',
            'opentracing': 'OpenTracing',
            'openebs': 'OpenEBS',
            'rook': 'Rook',
            'longhorn': 'Longhorn',
            'mayastor': 'Mayastor',
            'nfs': 'NFS',
            'samba': 'Samba',
            'ceph': 'Ceph',
            'glusterfs': 'GlusterFS',
            'minio': 'MinIO',
            'garage': 'Garage',
            'seaweedfs': 'SeaweedFS',
            'juicefs': 'JuiceFS',
            'alluxio': 'Alluxio',
            'presto': 'Presto',
            'trino': 'Trino',
            'drill': 'Apache Drill',
            'impala': 'Impala',
            'hive': 'Hive',
            'spark': 'Spark',
            'flink': 'Flink',
            'storm': 'Storm',
            'samza': 'Samza',
            'pulsar': 'Pulsar',
            'rocketmq': 'RocketMQ',
            'activemq': 'ActiveMQ',
            'ibm mq': 'IBM MQ',
            'tibco': 'TIBCO',
            'solace': 'Solace',
            'nats': 'NATS',
            'nsq': 'NSQ',
            'zeromq': 'ZeroMQ',
            'nanomsg': 'nanomsg',
            'dbus': 'D-Bus',
            'grpc': 'gRPC',
            'thrift': 'Thrift',
            'avro': 'Avro',
            'protobuf': 'Protocol Buffers',
            'protobufs': 'Protocol Buffers',
            'protocol buffers': 'Protocol Buffers',
            'flatbuffers': 'FlatBuffers',
            'capnproto': 'Cap\'n Proto',
            'messagepack': 'MessagePack',
            'msgpack': 'MessagePack',
            'bson': 'BSON',
            'cbor': 'CBOR',
            'apache arrow': 'Apache Arrow',
            'arrow': 'Apache Arrow',
            'parquet': 'Parquet',
            'orc': 'ORC',
            'delta lake': 'Delta Lake',
            'iceberg': 'Apache Iceberg',
            'hudi': 'Apache Hudi',
            'dbt': 'dbt',
            'data build tool': 'dbt',
            'airbyte': 'Airbyte',
            'fivetran': 'Fivetran',
            'stitch': 'Stitch',
            'meltano': 'Meltano',
            'singer': 'Singer',
            'hightouch': 'Hightouch',
            'census': 'Census',
            'reverse etl': 'Reverse ETL',
            'segment': 'Segment',
            'rudderstack': 'RudderStack',
            'snowplow': 'Snowplow',
            'matomo': 'Matomo',
            'plausible': 'Plausible',
            'amplitude': 'Amplitude',
            'mixpanel': 'Mixpanel',
            'heap': 'Heap',
            'posthog': 'PostHog',
            'june': 'June',
            'statsig': 'Statsig',
            'launchdarkly': 'LaunchDarkly',
            'unleash': 'Unleash',
            'flagsmith': 'Flagsmith',
            'split': 'Split',
            'optimizely': 'Optimizely',
            'growthbook': 'GrowthBook',
            'figma': 'Figma',
            'sketch': 'Sketch',
            'adobe xd': 'Adobe XD',
            'invision': 'InVision',
            'framer': 'Framer',
            'webflow': 'Webflow',
            'bubble': 'Bubble',
            'retool': 'Retool',
            'appsmith': 'Appsmith',
            'tooljet': 'ToolJet',
            'budibase': 'Budibase',
            'outsystems': 'OutSystems',
            'mendix': 'Mendix',
            'powerapps': 'Power Apps',
            'power apps': 'Power Apps',
            'appian': 'Appian',
            'servicenow': 'ServiceNow',
            'salesforce': 'Salesforce',
            'apex': 'Apex',
            'visualforce': 'Visualforce',
            'lightning': 'Lightning',
            'lwc': 'Lightning Web Components',
            'heroku': 'Heroku',
            'force.com': 'Force.com',
            'workbench': 'Workbench',
            'dataloader': 'Data Loader',
            'tableau': 'Tableau',
            'powerbi': 'Power BI',
            'power bi': 'Power BI',
            'looker': 'Looker',
            'metabase': 'Metabase',
            'superset': 'Apache Superset',
            'redash': 'Redash',
            'mode': 'Mode',
            'hex': 'Hex',
            'count': 'Count',
            ' Observable': 'Observable',
            'jupyter': 'Jupyter',
            'jupyterhub': 'JupyterHub',
            'jupyternotebook': 'Jupyter Notebook',
            'jupyternotebooks': 'Jupyter Notebooks',
            'google colab': 'Google Colab',
            'colab': 'Colab',
            'kaggle': 'Kaggle',
            'dagster': 'Dagster',
            'prefect': 'Prefect',
            'flyte': 'Flyte',
            'kedro': 'Kedro',
            'zenml': 'ZenML',
            'great expectations': 'Great Expectations',
            'pandera': 'Pandera',
            'pydantic': 'Pydantic',
            'attrs': 'attrs',
            'marshmallow': 'Marshmallow',
            'cerberus': 'Cerberus',
            'voluptuous': 'Voluptuous',
            'schema': 'Schema',
            'jsonschema': 'JSON Schema',
            'cerberus': 'Cerberus',
            'colander': 'Colander',
            'schematics': 'Schematics',
            'django rest framework': 'Django REST Framework',
            'drf': 'DRF',
            'tastypie': 'Tastypie',
            'graphene': 'Graphene',
            'strawberry': 'Strawberry',
            'ariadne': 'Ariadne',
            'tartiflette': 'Tartiflette',
            'asyncio': 'asyncio',
            'trio': 'Trio',
            'anyio': 'AnyIO',
            'curio': 'Curio',
            'gevent': 'Gevent',
            'eventlet': 'Eventlet',
            'twisted': 'Twisted',
            'tornado': 'Tornado',
            'flask-socketio': 'Flask-SocketIO',
            'socket.io': 'Socket.IO',
            'socketio': 'Socket.IO',
            'websockets': 'websockets',
            'wsproto': 'wsproto',
            'starlette': 'Starlette',
            'httptools': 'httptools',
            'h11': 'h11',
            'h2': 'h2',
            'hypercorn': 'Hypercorn',
            'daphne': 'Daphne',
            'uvicorn': 'Uvicorn',
            'gunicorn': 'Gunicorn',
            'meinheld': 'Meinheld',
            'bjoern': 'bjoern',
            'waitress': 'Waitress',
            'cheroot': 'Cheroot',
            'mod_wsgi': 'mod_wsgi',
            'passenger': 'Passenger',
            'phusion passenger': 'Phusion Passenger',
            'puma': 'Puma',
            'unicorn': 'Unicorn',
            'thin': 'Thin',
            'rainbows': 'Rainbows',
            'falcon': 'Falcon',
            'rack': 'Rack',
            'hanami': 'Hanami',
            'sinatra': 'Sinatra',
            'roda': 'Roda',
            'grape': 'Grape',
            'cuba': 'Cuba',
            'ramaze': 'Ramaze',
            'camping': 'Camping',
            'padrino': 'Padrino',
            'lotus': 'Lotus',
            'trailblazer': 'Trailblazer',
            'dry-rb': 'dry-rb',
            'rom': 'ROM',
            'sequel': 'Sequel',
            'activerecord': 'Active Record',
            'active record': 'Active Record',
            'datamapper': 'DataMapper',
            'mongoid': 'Mongoid',
            'ohm': 'Ohm',
            'redis-objects': 'Redis::Objects',
            'sidekiq': 'Sidekiq',
            'resque': 'Resque',
            'delayed job': 'Delayed Job',
            'sucker punch': 'Sucker Punch',
            'shoryuken': 'Shoryuken',
            'sqs workers': 'SQS Workers',
            'active job': 'Active Job',
            'backburner': 'Backburner',
            'que': 'Que',
            'good job': 'Good Job',
            'solid queue': 'Solid Queue',
            'sneakers': 'Sneakers',
            'karafka': 'Karafka',
            'racecar': 'Racecar',
            'waterdrop': 'WaterDrop',
            'deimos': 'Deimos',
            'phobos': 'Phobos',
        }

        # Standard job titles with proper capitalization
        job_titles_map = {
            'software engineer': 'Software Engineer',
            'software developer': 'Software Developer',
            'senior software engineer': 'Senior Software Engineer',
            'senior software developer': 'Senior Software Developer',
            'lead software engineer': 'Lead Software Engineer',
            'staff software engineer': 'Staff Software Engineer',
            'principal software engineer': 'Principal Software Engineer',
            'data scientist': 'Data Scientist',
            'data analyst': 'Data Analyst',
            'data engineer': 'Data Engineer',
            'senior data scientist': 'Senior Data Scientist',
            'senior data analyst': 'Senior Data Analyst',
            'senior data engineer': 'Senior Data Engineer',
            'machine learning engineer': 'Machine Learning Engineer',
            'ml engineer': 'ML Engineer',
            'ai engineer': 'AI Engineer',
            'devops engineer': 'DevOps Engineer',
            'site reliability engineer': 'Site Reliability Engineer',
            'sre': 'SRE',
            'platform engineer': 'Platform Engineer',
            'cloud engineer': 'Cloud Engineer',
            'infrastructure engineer': 'Infrastructure Engineer',
            'security engineer': 'Security Engineer',
            'cybersecurity engineer': 'Cybersecurity Engineer',
            'network engineer': 'Network Engineer',
            'systems engineer': 'Systems Engineer',
            'backend engineer': 'Backend Engineer',
            'backend developer': 'Backend Developer',
            'frontend engineer': 'Frontend Engineer',
            'frontend developer': 'Frontend Developer',
            'full stack engineer': 'Full Stack Engineer',
            'fullstack engineer': 'Full Stack Engineer',
            'full stack developer': 'Full Stack Developer',
            'fullstack developer': 'Full Stack Developer',
            'web developer': 'Web Developer',
            'mobile developer': 'Mobile Developer',
            'mobile engineer': 'Mobile Engineer',
            'ios developer': 'iOS Developer',
            'ios engineer': 'iOS Engineer',
            'android developer': 'Android Developer',
            'android engineer': 'Android Engineer',
            'react native developer': 'React Native Developer',
            'flutter developer': 'Flutter Developer',
            'game developer': 'Game Developer',
            'unity developer': 'Unity Developer',
            'qa engineer': 'QA Engineer',
            'quality assurance engineer': 'QA Engineer',
            'test engineer': 'Test Engineer',
            'automation engineer': 'Automation Engineer',
            'sdet': 'SDET',
            'product manager': 'Product Manager',
            'technical product manager': 'Technical Product Manager',
            'program manager': 'Program Manager',
            'project manager': 'Project Manager',
            'technical program manager': 'Technical Program Manager',
            'engineering manager': 'Engineering Manager',
            'engineering lead': 'Engineering Lead',
            'tech lead': 'Tech Lead',
            'team lead': 'Team Lead',
            'cto': 'CTO',
            'chief technology officer': 'CTO',
            'vp of engineering': 'VP of Engineering',
            'head of engineering': 'Head of Engineering',
            'director of engineering': 'Director of Engineering',
            'ux designer': 'UX Designer',
            'ui designer': 'UI Designer',
            'ui/ux designer': 'UI/UX Designer',
            'product designer': 'Product Designer',
            'graphic designer': 'Graphic Designer',
            'web designer': 'Web Designer',
            'interaction designer': 'Interaction Designer',
            'visual designer': 'Visual Designer',
            'motion designer': 'Motion Designer',
            'systems architect': 'Systems Architect',
            'software architect': 'Software Architect',
            'solutions architect': 'Solutions Architect',
            'enterprise architect': 'Enterprise Architect',
            'cloud architect': 'Cloud Architect',
            'data architect': 'Data Architect',
            'security architect': 'Security Architect',
            'technical architect': 'Technical Architect',
            'database administrator': 'Database Administrator',
            'dba': 'DBA',
            'sysadmin': 'Systems Administrator',
            'systems administrator': 'Systems Administrator',
            'network administrator': 'Network Administrator',
            'it administrator': 'IT Administrator',
            'it support': 'IT Support',
            'helpdesk': 'Helpdesk',
            'technical support': 'Technical Support',
            'customer support engineer': 'Customer Support Engineer',
            'sales engineer': 'Sales Engineer',
            'solutions engineer': 'Solutions Engineer',
            'pre-sales engineer': 'Pre-Sales Engineer',
            'business analyst': 'Business Analyst',
            'technical business analyst': 'Technical Business Analyst',
            'systems analyst': 'Systems Analyst',
            'financial analyst': 'Financial Analyst',
            'research analyst': 'Research Analyst',
            'marketing analyst': 'Marketing Analyst',
            'growth engineer': 'Growth Engineer',
            'seo specialist': 'SEO Specialist',
            'sem specialist': 'SEM Specialist',
            'content strategist': 'Content Strategist',
            'technical writer': 'Technical Writer',
            'documentation engineer': 'Documentation Engineer',
            'developer advocate': 'Developer Advocate',
            'developer relations': 'Developer Relations',
            'community manager': 'Community Manager',
            'open source maintainer': 'Open Source Maintainer',
            'scrum master': 'Scrum Master',
            'agile coach': 'Agile Coach',
            'release engineer': 'Release Engineer',
            'build engineer': 'Build Engineer',
            'performance engineer': 'Performance Engineer',
            'site performance engineer': 'Site Performance Engineer',
            'reliability engineer': 'Reliability Engineer',
            'analytics engineer': 'Analytics Engineer',
            'business intelligence engineer': 'BI Engineer',
            'bi developer': 'BI Developer',
            'etl developer': 'ETL Developer',
            'data warehouse engineer': 'Data Warehouse Engineer',
            'big data engineer': 'Big Data Engineer',
            'nlp engineer': 'NLP Engineer',
            'computer vision engineer': 'Computer Vision Engineer',
            'robotics engineer': 'Robotics Engineer',
            'embedded engineer': 'Embedded Engineer',
            'firmware engineer': 'Firmware Engineer',
            'hardware engineer': 'Hardware Engineer',
            'fpga engineer': 'FPGA Engineer',
            'asic engineer': 'ASIC Engineer',
            'chip design engineer': 'Chip Design Engineer',
            'vlsi': 'VLSI Engineer',
            'silicon engineer': 'Silicon Engineer',
        }

        # Common industries with proper capitalization
        industries_map = {
            'fintech': 'Fintech',
            'financial technology': 'Fintech',
            'healthcare': 'Healthcare',
            'health tech': 'Health Tech',
            'medtech': 'MedTech',
            'ecommerce': 'E-commerce',
            'e-commerce': 'E-commerce',
            'retail': 'Retail',
            'saas': 'SaaS',
            'software as a service': 'SaaS',
            'education': 'Education',
            'edtech': 'EdTech',
            'gaming': 'Gaming',
            'games': 'Gaming',
            'finance': 'Finance',
            'banking': 'Banking',
            'investment banking': 'Investment Banking',
            'insurance': 'Insurance',
            'insurtech': 'InsurTech',
            'manufacturing': 'Manufacturing',
            'automotive': 'Automotive',
            'aerospace': 'Aerospace',
            'defense': 'Defense',
            'government': 'Government',
            'public sector': 'Public Sector',
            'nonprofit': 'Nonprofit',
            'non-profit': 'Nonprofit',
            'energy': 'Energy',
            'renewable energy': 'Renewable Energy',
            'cleantech': 'CleanTech',
            'oil and gas': 'Oil & Gas',
            'telecommunications': 'Telecommunications',
            'telecom': 'Telecom',
            'media': 'Media',
            'entertainment': 'Entertainment',
            'streaming': 'Streaming',
            'social media': 'Social Media',
            'advertising': 'Advertising',
            'adtech': 'AdTech',
            'marketing': 'Marketing',
            'martech': 'MarTech',
            'real estate': 'Real Estate',
            'prop tech': 'PropTech',
            'proptech': 'PropTech',
            'logistics': 'Logistics',
            'supply chain': 'Supply Chain',
            'transportation': 'Transportation',
            'travel': 'Travel',
            'hospitality': 'Hospitality',
            'food delivery': 'Food Delivery',
            'agriculture': 'Agriculture',
            'agtech': 'AgTech',
            'construction': 'Construction',
            'contech': 'ConTech',
            'legal': 'Legal',
            'legal tech': 'LegalTech',
            'crypto': 'Cryptocurrency',
            'cryptocurrency': 'Cryptocurrency',
            'blockchain': 'Blockchain',
            'web3': 'Web3',
            'nft': 'NFT',
            'artificial intelligence': 'AI',
            'ai industry': 'AI',
            'machine learning industry': 'Machine Learning',
            'data science industry': 'Data Science',
            'quantum computing': 'Quantum Computing',
            'robotics': 'Robotics',
            'automation': 'Automation',
            'iot': 'IoT',
            'internet of things': 'IoT',
        }

        # Extract tech skills
        for skill_key, display_name in tech_skills_map.items():
            if skill_key in text:
                tag = self._get_or_create_tag(display_name, 'skill')
                if tag not in tags:
                    tags.append(tag)

        # Extract job titles (multi-word first, then single)
        # Sort by length (longest first) to prioritize specific titles
        sorted_titles = sorted(job_titles_map.items(), key=lambda x: len(x[0]), reverse=True)
        for title_key, display_name in sorted_titles:
            if title_key in text:
                tag = self._get_or_create_tag(display_name, 'role')
                if tag not in tags:
                    tags.append(tag)

        # Extract industries
        for industry_key, display_name in industries_map.items():
            if industry_key in text:
                tag = self._get_or_create_tag(display_name, 'industry')
                if tag not in tags:
                    tags.append(tag)

        return tags
    
    def _get_or_create_tag(self, name: str, category: str) -> Tag:
        tag = self.db.query(Tag).filter(Tag.name == name).first()
        if not tag:
            tag = Tag(name=name, category=category)
            self.db.add(tag)
            self.db.commit()
            self.db.refresh(tag)
        return tag
    
    def get_all_tags(self) -> List[Tag]:
        return self.db.query(Tag).all()
    
    def get_tags_by_category(self, category: str) -> List[Tag]:
        return self.db.query(Tag).filter(Tag.category == category).all()
